title: Kathy-Ann Heitmeier # your name (or website title) here
logo: "/images/heitmeier_round.png?raw=true" # your photo (or logo) here
description: 
  <br>
  User Experience researcher and Learning Experience designer with mixed-methods skills. I derive insights into user and learner experiences with products and services.
  <br><br>
  <a href="https://www.linkedin.com/in/kathy-ann-heitmeier/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here

github:
  is_project_page: false
