title: Kathy-Ann Heitmeier # your name (or website title) here
logo: "/images/heitmeier_round.png?raw=true" # your photo (or logo) here
description: 
  <br>
  Data analysis and data science professional with a background in computational linguistics. I combine my linguistics expertise and technical proficiency to derive insights into user and customer experiences with products and services.
  <br><br>
  <a href="https://www.linkedin.com/in/kathy-ann-heitmeier/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here

github:
  is_project_page: false
